use icons from icon theme
Bzero/typstwriter pull request #1
Opened 2024-06-19 16:27 UTC by tgilgien

This commit makes the app try to use the icons from the current icon theme, and falls back to the bundled ones if none is available.

Icon recoloring is not supported, so themes relying on it (e.g. breeze dark) will look broken (dark icons on dark background). Note that the current implementation always use dark icons even when using a dark color scheme.

2024-06-19 19:53 UTC, Bzero commented
Thanks a lot for this pull request! Using the icon theme does make sense and hopefully makes the application look a bit more native for users that prefer that. 

Could you please run `ruff check` and make sure that your changes adhere to the ruff linting and formatting rules? (I'm sorry that there is no github action in place yet that automatically enforces this, I will add that shorty).

2024-06-19 20:01 UTC, Bzero requested changes

2024-06-20 09:39 UTC, tgilgien commented on typstwriter/editor.py
> +            self.label_w.setPixmap(QtGui.QIcon.fromTheme(QtGui.QIcon.DialogWarning).pixmap(64))
Resolved, also changed in the if statement

2024-06-20 09:58 UTC, tgilgien commented
Thanks for the feedback!

I made the necessary changes to pass ``ruff check``. (Btw, I'm rather new to python development, so don't hesitate to be harsh on style)

2024-06-20 12:57 UTC, Bzero commented
Great, this is all looking good to me.

> I made the necessary changes to pass `ruff check`. (Btw, I'm rather new to python development, so don't hesitate to be harsh on style)

I think a quick `ruff format` will fix the remaining formatting issues. I am myself not very picky about code style or formatting but I think following a standard eases the collaboration when multiple people work on a project.

2024-06-20 14:00 UTC, merged

2024-06-20 14:00 UTC, Bzero commented
Thanks a lot for your work, very much appreciated!